### PR TITLE
Add Kelp rsETH token

### PR DESCRIPTION
**Pull request by rahuljaguste**

### CODE REVIEW

**Review by philippe-git — CHANGES_REQUESTED** [review]
Hi, in the endpoint mentioned in the readme (https://yields.llama.fi/pools) I'm not seeing any entry that has both `"symbol": "RSETH"` and `"project": "kelp"`, so this will not be able to match anything. Perhaps RSETH info is available in another entry on the defillama API, or perhaps you'll need to add it to defillama?

**Comment by rahuljaguste** [comment]
The response is big and easy to miss out. Use Firefox or output to JSON file with curl.  Please see the screenshot attached.
Screenshot 2024-07-01 at 5 29 02 PM

**Comment by philippe-git** [comment]
Yes, so from your screenshot it appears that the reason that I didn't find any entry with `project === 'kelp'` is because in the defillama api, the entry you want has `project === 'kelp-dao'`. Please use the exact same `project` id in your PR so the system can find the correct entry.

**Comment by rahuljaguste** [comment]
Have updated the same. Please check.

**Review by philippe-git — APPROVED** [review]
Looks perfect, thank you! Merging now, note that it'll take some time for the update to propagate through caches!

**Comment by rahuljaguste** [comment]
Thank you @philippe-git

**Pull request merged**
